export type { IProducer, IProducerJson } from "./IProducer"
export type { IProducerStatus } from "./IProducerStatus"
export type { IPoints } from "./IPoints"

export type { IEosIoChainGetGlobal } from "./IEosIoChainGetGlobal"
export type { IEosIoChainGetProducers } from "./IEosIoChainGetProducers"
export type { IEosIoChainGetProducerJson } from "./IEosIoChainGetProducerJson"
export type { IEosIoChainGetAccount } from "./IEosIoChainGetAccount"
export type { IEosIoChainGetInfo } from "./IEosIoChainGetInfo"
export type { IEosIoChainGetTableRows } from "./IEosIoChainGetTableRows"
