#!/usr/bin/env node
var http = require('http');
var fs = require('fs');
var documentRoot = './';
var server= http.createServer(function(req,res){
    var url = (req.url == "/") ? "/index.html" : req.url; 
    var file = documentRoot + url;
    console.log(url);
    fs.readFile( file , function(err,data){
        data = (err) ? '<p>404</p>' : data;
        res.writeHeader(200);
        res.write(data);
        res.end();
    });
}).listen(80);

console.log('http://localhost:80/');
